### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by dcsan** [agraebe/docs-nft#4]
running this repo gives the error below

trying to see what might be causing it with this
https://reactjs.org/warnings/invalid-hook-call-warning.html

```
➜  nft-nyc-exclusive-app git:(master) next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully in 2.5s (1015 modules)
wait  - compiling /...
event - compiled successfully in 1761 ms (1553 modules)
wait  - compiling /_error...
event - compiled successfully in 99 ms (1554 modules)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/dc/dev/esclabs/stan/nft-nyc-exclusive-app/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (/Users/dc/dev/esclabs/stan/nft-nyc-exclusive-app/node_modules/react/cjs/react.development.js:1484:20)
    at Html (webpack-internal:///../../../../.nvm/versions/node/v16.11.1/lib/node_modules/next/dist/pages/_document.js:153:73)
    at processChild (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/dist/server/render.js:739:41)
    at async doRender (/Users/dc/.nvm/versions/node/v16.11.1/lib/node_modules/next/dist/server/next-server.js:1389:38)
```

**Comment by dcsan** [comment]
it seems this is something to do with the SSR which is usually the case with next. I [ripped all that out](https://dev.to/apkoponen/how-to-disable-server-side-rendering-ssr-in-next-js-1563) and it seems to launch the client now but fails 

```
POST http://localhost:3999/v2/contracts/call-read/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM/nft-nyc-exclusive/get-last-token-id net::ERR_CONNECTION_REFUSED
```

so i'm assuming there's a server side needed to run this app which wasn't published in this repo. Is that somewhere else?
oh that's a local chain instance. 

how do I set this app to run against testnet for example?

either way it's nice to see the components used client side, but since the app depends on a wallet it might be far simpler to just use create-react-app ?
